// Generated by Bun plugin at 3/22/2026, 11:15:31 AM
declare namespace NodeJS {
    export interface ProcessEnv {
		DATABASE_URL: string
		DATA_CENTER: string
		KEYSPACE: string
		HASH_SALT: string
		JWT_PRIVATE: string
		AUTH_POSTGRES_URL: string
		BETTER_AUTH_SECRET: string
		BETTER_AUTH_URL: string
		REDIS_URL: string
		CLIENT_ORIGIN: string
    }
}


//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

