// Generated by Bun plugin at 3/3/2026, 6:30:57 PM
declare namespace NodeJS {
    export interface ProcessEnv {
		DATABASE_URL: string
		DATA_CENTER: string
		KEYSPACE: string
		HASH_SALT: string
		JWT_PRIVATE: string
		AUTH_POSTGRES_URL: string
		BETTER_AUTH_SECRET: string
		BETTER_AUTH_URL: string
		REDIS_URL: string
    }
}


//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

