// Generated by Bun plugin at 3/1/2026, 2:50:33 AM
declare namespace NodeJS {
    export interface ProcessEnv {
		DATABASE_URL: string
		DATA_CENTER: string
		KEYSPACE: string
		HASH_SALT: string
		JWT_PRIVATE: string
		AUTH_POSTGRES_URL: string
		BETTER_AUTH_SECRET: string
		BETTER_AUTH_URL: string
    }
}


//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

